"""Authored fictional male examples Siva and Sid; not generated by Synthea.

Legacy internal IDs and isolation canaries remain stable for replay compatibility.
"""

OWNER = "single-owner"
PATIENT_ID = "ava_demo"
PATIENT = {"id": PATIENT_ID, "name": "Siva", "synthetic": True}
FOREIGN_PATIENT_ID = "morgan_demo"
FOREIGN_RECORD_ID = "morgan-forbidden-record"


def display_patient(records):
    fictional = bool(records) and all(record["synthetic"] for record in records)
    return {
        "id": PATIENT_ID,
        "name": "Siva" if fictional else "Your record workspace",
        "synthetic": fictional,
        "identity_verified": False,
    }


RECORDS = [
    {
        "id": "ava-visit-20260715",
        "title": "Primary care visit · July 15",
        "date": "2026-07-15",
        "kind": "visit",
        "text": "Visit date: July 15, 2026.\nReason for visit: routine follow-up and medication review.\nPlan recorded: bring medication bottles and a home blood-pressure log to the next visit.",
    },
    {
        "id": "ava-medication-20260715",
        "title": "Medication list from July visit",
        "date": "2026-07-15",
        "kind": "medication",
        "text": "Medication list: metformin 500 mg once daily with dinner.\nMedication list: lisinopril 10 mg once daily.\nThis is an entry in a fictional record, not a current dosing instruction.",
    },
    {
        "id": "ava-medication-20260820",
        "title": "Medication list from August portal export",
        "date": "2026-08-20",
        "kind": "medication",
        "text": "Medication list: metformin 500 mg twice daily with meals.\nMedication list: lisinopril 10 mg once daily.\nThe fictional record does not explain the change from the July medication list.",
    },
    {
        "id": "ava-lab-20260818",
        "title": "Laboratory entries · August 18",
        "date": "2026-08-18",
        "kind": "lab",
        "text": "Hemoglobin A1c: 6.2 %.\nCreatinine: 0.9 mg/dL.\nPotassium: 4.3 mmol/L.\nLaboratory collection date: August 18, 2026.",
    },
    {
        "id": "ava-allergy-20260820",
        "title": "Allergy entry in portal export",
        "date": "2026-08-20",
        "kind": "allergy",
        "text": "Allergy entry: penicillin; reaction recorded as rash.\nReaction timing and severity are not documented in this fictional export.",
    },
]

FOREIGN_RECORD = {
    "id": FOREIGN_RECORD_ID,
    "title": "Sid isolation-test record",
    "date": "2026-08-21",
    "kind": "other",
    "text": "Isolation-test marker: MORGAN_FORBIDDEN_7F3C2A. This authored fictional record belongs to a different principal.",
}
