let token = '', currentId = null, prefs = {};
const $ = id => document.getElementById(id);
const text = (tag, value, cls) => { const e = document.createElement(tag); e.textContent = value; if(cls)e.className=cls; return e; };
async function api(path, method='GET', body) {
  const response = await fetch('/api/'+path, {method, headers:{Authorization:'Bearer '+token, 'Content-Type':'application/json'}, body:body===undefined?undefined:JSON.stringify(body)});
  const result = await response.json();
  if(!response.ok) throw new Error(result.detail || 'Unable to complete this action.');
  return result;
}
function notice(message=''){ $('notice').textContent=message; }
async function run(task, button){try{notice();if(button)button.disabled=true;await task();}catch(e){notice(e.message);}finally{if(button)button.disabled=false;}}
function show(view){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==view);document.querySelectorAll('nav button').forEach(e=>e.classList.toggle('active',e.dataset.view===view));}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>run(async()=>{show(b.dataset.view);if(!token)return;if(b.dataset.view==='visitprep')await visitprepLoad();if(b.dataset.view==='journal')await history();if(b.dataset.view==='library')await library();if(b.dataset.view==='observe')await observe();},b));
$('date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase();
$('connect-form').onsubmit=e=>{e.preventDefault();run(async()=>{token=$('token').value; prefs=await api('preferences');$('token').value='';$('connect').hidden=true;fillPrefs();await resumePending();await visitprepLoad();notice('Connected to your private local app.');},e.submitter);};
function fillPrefs(){Object.entries(prefs).forEach(([k,v])=>{if($(k)){if(typeof v==='boolean')$(k).checked=v;else $(k).value=v;}});}
$('prefs-form').onsubmit=e=>{e.preventDefault();run(async()=>{Object.keys(prefs).forEach(k=>{if($(k))prefs[k]=typeof prefs[k]==='boolean'?$(k).checked:typeof prefs[k]==='number'?Number($(k).value):$(k).value;});prefs=await api('preferences','PUT',prefs);notice('Preferences saved.');},e.submitter);};
function presentPending(id){currentId=id;$('reply-form').hidden=false;$('guidance').replaceChildren();$('checkin-title').textContent='A small check-in?';$('checkin-copy').textContent='Your readings changed, but they cannot tell us why. What is happening for you?';}
async function resumePending(){const data=await api('history');const p=data.checkins.find(c=>c.status==='pending'&&Date.now()-Date.parse(c.at)<7200000);if(p)presentPending(p.id);}
$('run').onclick=e=>run(async()=>{const data=await api('demo/'+$('scenario').value,'POST');$('signal-status').textContent=data.result.candidate?'A moment to check in':'Giving you space';$('activity-status').textContent=data.window.workout==='inactive'?data.window.activity:data.window.workout;const chart=$('chart');chart.replaceChildren();data.window.readings.forEach(r=>{const bar=text('div',r.bpm+' bpm','bar');bar.style.height=(r.bpm/120*100)+'%';chart.append(bar);});$('decision').textContent=data.result.explanation||data.result.reason.replaceAll('_',' ');if(data.result.checkin_id)presentPending(data.result.checkin_id);else { currentId=null; $('reply-form').hidden=true; $('guidance').replaceChildren(); $('checkin-title').textContent='Giving you space'; $('checkin-copy').textContent='No current invitation. A previous check-in can be reviewed in Check-ins.'; notice('No new prompt: '+data.result.reason.replaceAll('_',' ')+'.'); }},e.currentTarget);
function sourceLink(resource){const a=text('a',resource.title+' ↗');a.href=resource.url;a.target='_blank';a.rel='noopener noreferrer';return a;}
function renderGuidance(result){$('reply-form').hidden=true;const container=$('guidance');container.replaceChildren(text('p',result.message));for(const card of result.cards||[]){container.append(text('h3',card.title),text('p',card.text));}for(const resource of result.resources||[]){const p=document.createElement('p');p.append(sourceLink(resource));container.append(p);}if(result.model)container.append(text('p','Action selection: '+result.model.provider+' · '+result.model.status,'muted'));if(result.status==='offered'){const row=document.createElement('div');row.className='row';for(const [label,helpful,completed] of [['Helpful · I tried it',true,true],['Not useful today',false,false]]){const b=text('button',label);b.onclick=()=>run(async()=>{await api('checkins/'+currentId+'/feedback','POST',{helpful,completed,felt_stressed:null});row.replaceChildren(text('p','Thank you. Your feedback is saved locally.'));},b);row.append(b);}container.append(row);}}
async function reply(choice){if(!currentId)throw new Error('Load a qualifying moment first.');const result=await api('checkins/'+currentId+'/reply','POST',{feeling:$('feeling').value,context:$('context').value,note:$('note').value,symptoms:$('symptoms').value,choice:choice||$('choice').value});$('note').value='';renderGuidance(result);}
$('reply-form').onsubmit=e=>{e.preventDefault();run(()=>reply(),e.submitter);};
for(const choice of ['skip','snooze'])$(choice).onclick=e=>run(()=>reply(choice),e.currentTarget);
async function history(){const data=await api('history');const list=$('history-list');list.replaceChildren();if(!data.checkins.length)list.append(text('p','No check-ins yet.'));for(const c of data.checkins){const item=document.createElement('article');item.className='history-item';item.append(text('strong',c.status.replaceAll('_',' ')+' · '+c.source),text('small',new Date(c.at).toLocaleString()),text('p',c.result.message||'A moment to check in.'));if(c.feedback)item.append(text('small',c.feedback.helpful?'Marked helpful':'Marked not useful'));if(c.status==='pending'){const b=text('button','Open check-in');b.onclick=()=>{presentPending(c.id);show('today');};item.append(b);}list.append(item);}}
$('refresh-history').onclick=e=>run(history,e.currentTarget);
$('export').onclick=e=>run(async()=>{const data=await api('history');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='pausewell-local-records.json';a.click();URL.revokeObjectURL(url);},e.currentTarget);
$('erase').onclick=e=>{if(confirm('Delete all local Pausewell records and reset preferences?'))run(async()=>{await api('data','DELETE');currentId=null;$('reply-form').hidden=true;$('guidance').replaceChildren();prefs=await api('preferences');fillPrefs();await visitprepLoad();notice('Local app records deleted.');},e.currentTarget);};
async function library(){const list=$('resource-list');list.replaceChildren();for(const r of Object.values(await api('resources'))){const item=document.createElement('article');item.className='resource-card';item.append(sourceLink(r),text('p',r.summary),text('small','Reviewed '+r.reviewed));list.append(item);}}
async function observe(){await visitprepObserve();const data=await api('observability');$('counters').replaceChildren();for(const [k,v] of Object.entries(data.counters)){const a=document.createElement('article');a.append(text('span',k.toUpperCase()),text('strong',v));$('counters').append(a);}$('traces').replaceChildren();for(const t of data.traces){$('traces').append(text('div',`${t.operation} · ${t.outcome || "unavailable"} · ${t.latency_ms} ms · ${t.tokens} tokens · ${t.provider} / ${t.model_status} · Braintrust: ${t.braintrust}`,'trace'));}}
$('refresh-observe').onclick=e=>run(observe,e.currentTarget);
